name: Food Power
url: https://curious-yu.github.io/foodpower/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

timezone: America/Los_Angeles

excerpt_separator: "<!-- more -->"

permalink: /resources/:title/
